lddt_admin_index:
    path:     /
    defaults: { _controller: LddtMainBundle:Admin:index }

lddt_admin_publish:
    path:     /published/{id}
    defaults: { _controller: LddtMainBundle:Admin:published }

