<?php
    namespace Lddt\MainBundle\Repository;
    /**
     * DrawRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class DrawRepository extends \Doctrine\ORM\EntityRepository{
    }
