lddt_main_homepage:
    path:     /
    defaults: { _controller: LddtMainBundle:Default:index }
#    Ici sont les routes local (contrainrement au app/config/routing.yml qui est un routing général)
lddt_main_create:
    path:     /create
    defaults: { _controller: LddtMainBundle:Default:create }

lddt_main_show:
    path:     /show/{id}
    defaults: { _controller: LddtMainBundle:Default:show }
